// This file was auto-generated by etc/meta/generate-resources.sh

#pragma once

namespace ogm::resource {

// object_resource.png
extern unsigned char object_resource_png[];
extern unsigned int object_resource_png_len;

} /* namespace ogm::resource */
